[2021-07-12 00:14:53,176] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Spark_S3_ETL.bootstrap_task_to_s3 2021-07-12T00:14:48.417221+00:00 [queued]>
[2021-07-12 00:14:53,220] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Spark_S3_ETL.bootstrap_task_to_s3 2021-07-12T00:14:48.417221+00:00 [queued]>
[2021-07-12 00:14:53,221] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-12 00:14:53,224] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-12 00:14:53,232] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-12 00:14:53,282] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): bootstrap_task_to_s3> on 2021-07-12T00:14:48.417221+00:00
[2021-07-12 00:14:53,307] {standard_task_runner.py:52} INFO - Started process 1030 to run task
[2021-07-12 00:14:53,323] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Spark_S3_ETL', 'bootstrap_task_to_s3', '2021-07-12T00:14:48.417221+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpjpm0f_l4', '--error-file', '/tmp/tmpk54du3dt']
[2021-07-12 00:14:53,326] {standard_task_runner.py:77} INFO - Job 26: Subtask bootstrap_task_to_s3
[2021-07-12 00:14:53,424] {logging_mixin.py:104} INFO - Running <TaskInstance: Spark_S3_ETL.bootstrap_task_to_s3 2021-07-12T00:14:48.417221+00:00 [running]> on host ae6e515e2a1e
[2021-07-12 00:14:53,535] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=CapstoneProject
AIRFLOW_CTX_DAG_ID=Spark_S3_ETL
AIRFLOW_CTX_TASK_ID=bootstrap_task_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-12T00:14:48.417221+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-12T00:14:48.417221+00:00
[2021-07-12 00:14:53,540] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: copy_to_s3() missing 1 required positional argument: 'bucket_name'
[2021-07-12 00:14:53,554] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=Spark_S3_ETL, task_id=bootstrap_task_to_s3, execution_date=20210712T001448, start_date=20210712T001453, end_date=20210712T001453
[2021-07-12 00:14:53,661] {local_task_job.py:151} INFO - Task exited with return code 1
